### ISSUE TITLE
versioning with carrierwave 

### ISSUE THREAD

**Issue by eveevans** [airblade/paper_trail#134]
When I try to version a Model that has a carrierwave object, PaperTrail try to stores the whole Ruby Object  (CarrierWave Uploader) instead of a string that would be the carrierwave url

> Example of version table, column object: 

```

---
name: Foo
photo: !ruby/object:PhotoUploader
  model: !ruby/object:Photo
    attributes:
      id: 2
      name:
      .................
```
