### ISSUE TITLE
rails 4: can't save my model, event is blank

### ISSUE THREAD

**Issue by pushcx** [airblade/paper_trail#253]
I'm updating an app from Rails 3.2 to 4 and pulled in the `rails4` branch of PaperTrail. I have a test failing, a model that can't be saved. The error message on the model is not useful:

```
messages:
  :versions:
  - is invalid
```

but when I dug into model.versions.first.errors, I found:

``` yaml
--- !ruby/object:ActiveModel::Errors
base: !ruby/object:GamerVersion
  attributes:
    id:
    item_type: Gamer
    item_id: 1
    event:
    whodunnit:
    object:
    created_at:
messages:
  :event:
  - can't be blank
```

No idea what's happening - all I'm doing is loading the model, changing one attribute, and saving. This was really just a test of a side effect that changing one column updates a timestamp.
