### ISSUE TITLE
Paper_trail creates a first version with the custom meta attribute `approved` set to false even when it should be true

### ISSUE THREAD

**Issue by duarme** [airblade/paper_trail#385]
The Content model has a bunch of attributes, but one of them is `approved` defined by this code in its migration:

```
add_column :contents, :approved, :boolean, null: false, default: false
```

And in its ContentVersion migration:

```
class CreateContentVersions < ActiveRecord::Migration
  def self.up
    create_table :content_versions do |t|
      t.string   :item_type, :null => false
      t.integer  :item_id,   :null => false
      t.string   :event,     :null => false
      t.boolean  :approved, null: false, default: false # <= this one
      t.string   :whodunnit
      t.text     :object
      t.text     :object_changes
      t.datetime :created_at
    end
    add_index :content_versions, [:item_type, :item_id]
  end
# ...
```

Of course, Content also has paper_trail:

```
# content.rb
has_paper_trail class_name: 'ContentVersion', meta: { approved: :approved }
```

This code creates and saves a content object:

```
content = Content.create!({
      author_id: user.id,
      content: Lorem.sentence,
      approved: true
    })
```

I expect it's first version to have `approved = true`, but, checking it via rails console it's easy to find out that `content.versions.first.approved` is `false`, while it should be `true`:

```
#!
- !ruby/object:ContentVersion
  attributes:
    id: 447
    item_type: Measure
    item_id: 42
    event: create
    approved: false
    whodunnit: '1'
    object: 
    object_changes: "--- !ruby/hash:[...]"
    created_at: 2014-06-20 10:08:59.263012000 Z
```

Why is that?
